options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs in Cloud Logging only

steps:

# Step to access the secret and save it to a file
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'retrieve-secret'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Retrieve the service account key from Secret Manager
      gcloud secrets versions access latest --secret="gcloudcliapp-sa-key" > /workspace/gcloudcliapp-sa-key.json
      
#      # Export the key location as an environment variable
#      export GOOGLE_APPLICATION_CREDENTIALS="/workspace/gcloudcliapp-sa-key.json"

#      # Build the Docker image
#      docker build . -t us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA' -f backend/Dockerfile --build-arg GOOGLE_APPLICATION_CREDENTIALS="/workspace/gcloudcliapp-sa-key.json"

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-backend-image'
  args:
    - 'build'
    - '-t'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
    - '--build-arg'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcloudcliapp-sa-key.json'
    - '-f'
    - 'backend/Dockerfile'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'tag-backend-image'
  args: [
    'tag',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest',
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-backend-image:commit'
  args: [
    'push',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
  ]

- name: 'gcr.io/cloud-builders/docker'
   id: 'push-backend-image:latest'
  args: [
    'push',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA',
    '-f', 'frontend/Dockerfile',
    'frontend'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'tag',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest',
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest'
  ]

images:
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest'
