options:
  logging: CLOUD_LOGGING_ONLY  # Optional, if you want logs in Cloud Logging only

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-backend-image'
  args:
    - 'build'
    - '--no-cache'
    - '-t'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
    - '-f'
    - 'backend/Dockerfile'
    - 'backend/'

- name: 'gcr.io/cloud-builders/docker'
  id: 'tag-backend-image'
  args:
    - 'tag'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-backend-image:commit'
  args:
    - 'push'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-backend-image:latest'
  args:
    - 'push'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend-image'
  args:
    - 'build'
    - '--no-cache'
    - '-t'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'
    - '-f'
    - 'frontend/Dockerfile'
    - 'frontend/'

- name: 'gcr.io/cloud-builders/docker'
  id: 'tag-frontend-image'
  args:
    - 'tag'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend-image:commit'
  args:
    - 'push'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend-image:latest'
  args:
    - 'push'
    - 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest'

images:
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:$COMMIT_SHA'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:$COMMIT_SHA'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest'
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest'