version: '3'
services:
  backend:
#   image: us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-backend:latest  # Use the prebuilt image
    image: backend-latest:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
#   image: us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli/gcloud-cli-frontend:latest  # Use the prebuilt image
    image: frontend-latest:latest
    ports:
      - "3000:80"

