version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
