steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli:$COMMIT_SHA']

images:
- 'us-west1-docker.pkg.dev/articulate-rain-321323/gcloud-cli:$COMMIT_SHA'
